version: '3'

networks:
  zabbix-net:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.240.0/20

services:
  postgres-server:
    image: postgres:latest
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_pwd
      - POSTGRES_DB=zabbix
    restart: unless-stopped
    networks:
      - zabbix-net

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:alpine-6.4-latest
    volumes:
      - /zbx_instance/snmptraps:/var/lib/zabbix/snmptraps:rw
      - /var/lib/zabbix/mibs:/usr/share/snmp/mibs:ro
    ports:
      - "162:1162/udp"
    restart: unless-stopped
    networks:
      - zabbix-net

  zabbix-server-pgsql:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    environment:
      - DB_SERVER_HOST=postgres-server
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_pwd
      - POSTGRES_DB=zabbix
      - ZBX_ENABLE_SNMP_TRAPS=true
    ports:
      - "10051:10051"
    volumes_from:
      - zabbix-snmptraps
    restart: unless-stopped
    networks:
      - zabbix-net

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    environment:
      - ZBX_SERVER_HOST=zabbix-server-pgsql
      - DB_SERVER_HOST=postgres-server
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_pwd
      - POSTGRES_DB=zabbix
    ports:
      - "443:8443"
      - "80:8080"
    volumes:
      - /etc/ssl/nginx:/etc/ssl/nginx:ro
    restart: unless-stopped
    networks:
      - zabbix-net